# -*- coding: utf-8 -*-
"""Brainfuck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5bP9FPvM8-Hk9leNWsIekfWLdup4hYo
"""

def generate_brainfuck_char(char):
    ascii_value = ord(char)
    # Initialize the base value
    brainfuck_code = "+"

    # Loop to create the base value
    loop_count = ascii_value // 10
    brainfuck_code += "[" + "-" * 3 + ">" + "+" * (loop_count * 2) + "<]"

    # Adjust to the exact value
    remainder = ascii_value % 10
    brainfuck_code += ">" + "+" * remainder + "."

    return brainfuck_code

def generate_brainfuck_alphabet():
    alphabet = "Aditya Gollapalli"
    brainfuck_code = ""
    for char in alphabet:
        brainfuck_code += generate_brainfuck_char(char)
        brainfuck_code += "\n"
    return brainfuck_code

brainfuck_alphabet_code = generate_brainfuck_alphabet()
print(brainfuck_alphabet_code)

